### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by kenmazaika** [jorboar/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by jorboar** [comment]
I believe I've got it fixed up.

**Comment by kenmazaika** [comment]
Thumbs up!  You added the tag perfectly!
